<a href="https://colab.research.google.com/github/alimoorreza/CS128-SP25-Assignment-2/blob/main/cs128_assignment_2_bayes_filtering_start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

###**Prior belief: $bel(X_0)$**
Belief reflects the robot’s internal knowledge about the state of the environment. Robot is estimating the state of the door using its camera sensor and manipulator. State $X_0$ can have one of two possible values: *{is_open, is_closed}*

In [79]:
# bel_bar(x) computation
bel_xt    = np.zeros(2)
bel_xt[0] = 0.5 # bel_x0(X_0=is_open)
bel_xt[1] = 0.5 # bel_x0(X_0=is_closed)
print(bel_xt)

[0.5 0.5]



###**Measurement probability distribution: $p(z_t|x_t)$**
It is probabilistic law according to which measurements are generated from the environment state $x$. The sensor measurement has two outcomes *{sense_open, sense_closed}*. Let's assume our sensor is noisy ie, when the robot is in a particular state, the sensor can predict the status of the door with some probability.

In [80]:
measurement_prob    = np.zeros(4)
measurement_prob[0] = 0.6   # p(zt_sense_open  | xt=is_open)
measurement_prob[1] = 0.4   # p(zt_sense_close | xt=is_open)
measurement_prob[2] = 0.2   # p(zt_sense_open  | xt=is_close)
measurement_prob[3] = 0.8   # p(zt_sense_close | xt=is_close)
print(measurement_prob)

[0.6 0.4 0.2 0.8]


###**State transition probability distribution $p(x_t|x_{t-1}, u_t)$**
It denotes how the environment states evolve over time as a function of robot control $u$. Let's assume that the robot's control has two values *{push, do_nothing}*. Robot uses its manipulator with *{push}* control then the state transition probabilities are as follows:

In [81]:
state_transition_prob       = np.zeros((2, 4))
state_transition_prob[0, 0] = 1.0   # p(xt_is_open  | xt-1=is_open,  ut = push)
state_transition_prob[0, 1] = 0.0   # p(xt_is_close | xt-1=is_open,  ut = push)
state_transition_prob[0, 2] = 0.8   # p(xt_is_open  | xt-1=is_close, ut = push)
state_transition_prob[0, 3] = 0.2   # p(xt_is_close | xt-1=is_close, ut = push)
print(state_transition_prob)

[[1.  0.  0.8 0.2]
 [0.  0.  0.  0. ]]


In [82]:
state_transition_prob[1, 0] = 1.0   # p(xt_is_open  | xt-1=is_open,  ut = do_nothing)
state_transition_prob[1, 1] = 0.0   # p(xt_is_close | xt-1=is_open,  ut = do_nothing)
state_transition_prob[1, 2] = 0.0   # p(xt_is_open  | xt-1=is_close, ut = do_nothing)
state_transition_prob[1, 3] = 1.0   # p(xt_is_close | xt-1=is_close, ut = do_nothing)
print(state_transition_prob)

[[1.  0.  0.8 0.2]
 [1.  0.  0.  1. ]]


###**Bayes Filter Algorithm for state estimation**
<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs128_sp25/bayes_filter_algorithm1.png" width=450/>
</div>

##Task#1  (4 points): Calculate posterior belief: $bel(x_1)$
Robot at time **t=1** uses manipulator control value *{do_nothing}* and robot's camera sensor at time t=1 senses a measurement value *{sense_open}*.

> Calculate the resulting posterior belief $bel(x_1)$ is calculated by Bayes Filter Algorithm.

> According to its posterior belief, what does the robot infer about whether the **door remains open or closes**?

Hint: You need to calculate the *Prediction step* and then *Measurement update step* as follows:
<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs128_sp25/bayes_filter_algorithm2.png" width=450/>
</div>

In [ ]:
# Prediction step: bel_xt_bar(x) computation
# Hint: look up the state_transition_prob (above) values to find the appropriate transition probabilities

bel_xt_bar        = np.zeros(2)
'''
# bel_xt_bar(X_1=is_open)
bel_xt_bar(X_1=is_open)     = p(x1_is_open  | x0=is_open,  ut = do_nothing)*bel_x0(X_0=is_open) +
                              p(x1_is_open  | x0=is_close,  ut = do_nothing)*bel_x0(X_0=is_close)
'''
bel_xt_bar[0]     = ?



'''
# bel_xt_bar(X_1=is_closed)
bel_xt_bar(X_1=is_closed)   = p(x1_is_closed  | x0=is_open,  ut = do_nothing)*bel_x0(X_0=is_open) +
                              p(x1_is_closed  | x0=is_close,  ut = do_nothing)*bel_x0(X_0=is_close)
'''

bel_xt_bar[1]     = ?
print(bel_xt_bar)

In [84]:
# Measurement update step: bel_xt(x) computation
# Hint: look up the measurement_prob (above) values to find the appropriate measurement probabilities

'''
measurement_prob[0] = 0.6   # p(zt_sense_open  | xt=is_open)
measurement_prob[1] = 0.4   # p(zt_sense_close | xt=is_open)
measurement_prob[2] = 0.2   # p(zt_sense_open  | xt=is_close)
measurement_prob[3] = 0.8   # p(zt_sense_close | xt=is_close)
print(measurement_prob)
'''

'''
# bel_xt(X_1=is_open)
bel_xt(X_1=is_open)     = eta * p(z1_sense_open | x1_is_open)*bel_xt_bar(X_1=is_open)
'''
bel_xt[0]       = ?


'''
# bel_xt(X_1=is_close)
bel_xt(X_1=is_open)     = eta * p(z1_sense_open | x1_is_close)*bel_xt_bar(X_1=is_close)
'''
bel_xt[1]       = ?

print(bel_xt)

norm_constant = (bel_xt[0] + bel_xt[1])
print(norm_constant)

# normalized posterior probability
bel_xt = bel_xt/norm_constant
print('Posterior belief bel(x1): ', bel_xt)

[0.3 0.1]
0.4
Posterior belief bel(x1):  [0.75 0.25]


##Task#2  (4 points): Calculate posterior belief: $bel(x_2)$
Robot at time **t=2** uses manipulator control value *{push}* and robot's camera sensor at time t=1 senses a measurement value *{sense_open}*.


> Calculate the resulting posterior belief $bel(x_2)$ is calculated by Bayes Filter Algorithm.

> According to its posterior belief, what does the robot infer about whether the **door remains open or closes**?

In [85]:
# Prediction step: bel_xt_bar(x) computation
# Hint: look up the state_transition_prob (above) values to find the appropriate transition probabilities
'''
state_transition_prob[0, 0] = 1.0   # p(xt_is_open  | xt-1=is_open,  ut = push)
state_transition_prob[0, 1] = 0.0   # p(xt_is_close | xt-1=is_open,  ut = push)
state_transition_prob[0, 2] = 0.8   # p(xt_is_open  | xt-1=is_close, ut = push)
state_transition_prob[0, 3] = 0.2   # p(xt_is_close | xt-1=is_close, ut = push)
'''

'''
# bel_xt_bar(X_1=is_open)
'''
bel_xt_bar[0]     = ?


'''
# bel_xt_bar(X_1=is_closed)
'''

bel_xt_bar[0]     = ?



[0.95 0.05]


In [ ]:
# Measurement update step: bel_xt(x) computation
# Hint: look up the measurement_prob (above) values to find the appropriate measurement probabilities

'''
measurement_prob[0] = 0.6   # p(zt_sense_open  | xt=is_open)
measurement_prob[1] = 0.4   # p(zt_sense_close | xt=is_open)
measurement_prob[2] = 0.2   # p(zt_sense_open  | xt=is_close)
measurement_prob[3] = 0.8   # p(zt_sense_close | xt=is_close)
print(measurement_prob)
'''

'''
# bel_xt(X_1=is_open)
'''
bel_xt[0]       = ?


'''
# bel_xt(X_1=is_close)
'''
bel_xt[1]       = ?
